# Generated by Django 5.0 on 2023-12-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Boys', max_length=6)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='AC', max_length=6)),
                ('occupancy', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], default='Single', max_length=6)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.floor')),
                ('residents', models.ManyToManyField(related_name='rooms', to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='hostel.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostel.wing'),
        ),
    ]
