# Generated by Django 5.0 on 2023-12-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_rename_name_room_number'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='residents',
            field=models.ManyToManyField(null=True, related_name='rooms', to='user.student'),
        ),
    ]
